GENIO: configs: genio_1200_evk_defconfig: Enlarge decompression buffer
The config CONFIG_SYS_BOOTM_LEN specifies the size of buffer used for
kernel decompression process. The default value (0x4000000, 64MiB) is
not sufficient for decompressing kernel image equal to or larger then
22.5MiB, which causes decompression failure:

====
 ## Loading kernel from FIT Image at 4a000000 ...
   Using 'conf-mediatek_mt8395-genio-1200-evk.dtb' configuration
   Verifying Hash Integrity ... OK
   Trying 'kernel-1' kernel subimage
     Description:  Linux kernel
     Created:      2025-01-23   6:46:26 UTC
     Type:         Kernel Image
     Compression:  gzip compressed
     Data Start:   0x4a000634
     Data Size:    23561399 Bytes = 22.5 MiB
     Architecture: AArch64
     OS:           Linux
     Load Address: 0x64000000
     Entry Point:  0x64000000
     Hash algo:    sha256
     Hash value:   dca07c03342aba7ad9d688d12d73ef5d91d942bc32592a85e66933fe295ec8e0
   Verifying Hash Integrity ... sha256+ OK
 ## Loading fdt from FIT Image at 4a000000 ...
......
   Uncompressing Kernel Image
Error: inflate() returned -5
gzip compressed: uncompress error -1
Must RESET board to recover
resetting ...
====

Now we increase the value of CONFIG_SYS_BOOTM_LEN to 0x5000000 (80MiB) to
fix the issue.

Change-Id: I076e6fc32e28f0b9769d1a7215a733a0ac8bef41
Signed-off-by: Ramax Lo <ramax.lo@mediatek.com>